### ISSUE TITLE
Unable to get workflow to work.

### ISSUE THREAD

**Issue by Erbenos** [elementary/website#2272]
## Describe the bug
Unable to get `npm run build && npm run start` to work. Followed CONTRIBUTING.md on Ubuntu 19.04 and Windows 10.

### To Reproduce
1. Follow CONTRIBUTING.md
2. Get to the point of `npm run build && npm run start`
3. See error

### Expected behavior
Ability to run website workflow so that its possible contribute.

### Logs
Here is terminal output:
```
mfoltyn@laptop:~/Projects/elementary/website$ npm run build && npm run start
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> mvp@0.4.0 build /home/mfoltyn/Projects/elementary/website
> gulp

[22:43:40] Failed to load external module @babel/register
[22:43:40] Requiring external module babel-register
[22:43:40] Using gulpfile ~/Projects/elementary/website/gulpfile.babel.js
[22:43:40] Starting 'default'...
[22:43:40] Starting 'images'...
[22:43:40] Starting 'styles'...
[22:43:40] Starting 'scripts'...
[22:43:40] Starting 'store'...
[22:43:40] Starting 'png'...
[22:43:40] Starting 'jpg'...
[22:43:40] Starting 'svg'...
[22:43:40] Starting 'gif'...
[22:43:41] 'svg' errored after 591 ms
[22:43:41] Error: File not found with singular glob: /home/mfoltyn/Projects/elementary/website/_images/icons/mimes/24/payment-card-amex.svg (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/mfoltyn/Projects/elementary/website/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:277:13)
    at Glob.emit (events.js:189:13)
    at Glob.EventEmitter.emit (domain.js:441:20)
    at Glob._finish (/home/mfoltyn/Projects/elementary/website/node_modules/glob/glob.js:197:8)
    at done (/home/mfoltyn/Projects/elementary/website/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/mfoltyn/Projects/elementary/website/node_modules/glob/glob.js:688:12)
    at /home/mfoltyn/Projects/elementary/website/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/mfoltyn/Projects/elementary/website/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/mfoltyn/Projects/elementary/website/node_modules/glob/glob.js:764:12)
[22:43:41] 'images' errored after 593 ms
[22:43:41] 'default' errored after 594 ms
[22:43:41] The following tasks did not complete: styles, scripts, store, png, jpg, gif
[22:43:41] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mvp@0.4.0 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mvp@0.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mfoltyn/.npm/_logs/2019-10-13T20_43_41_381Z-debug.log
```

Issue persists even after I updated npm to latest and rerun `npm i`.

Please check what applies:
-->
- I'm using the latest version from git

**Comment by lewisgoddard** [comment]
The important issue is this line:

`Error: File not found with singular glob: /home/mfoltyn/Projects/elementary/website/_images/icons/mimes/24/payment-card-amex.svg (if this was purposeful, use 'allowEmpty' option)`

This is because [`gulpfile.babel.js` Line 100](https://github.com/elementary/website/blob/master/gulpfile.babel.js#L100) explicitly lists what icons to build in the submodule. If that submodule falls out of sync, then the build fails.

**Comment by Erbenos** [comment]
Shouldnt submodules be copied over when I clone the main repo? I dont recall needing to download / upadtes submodules separately. I dont use them.

**Comment by Erbenos** [comment]
Now, `npm run build` hangs with following output:

```
C:\Work Projects\elementary>npm run build                                                                                                                                                                                                       > mvp@0.4.0 build C:\Work Projects\elementary                                                                           > gulp                                                                                                                                                                                                                                          [21:38:30] Requiring external module babel-register                                                                     [21:38:32] Using gulpfile C:\Work Projects\elementary\gulpfile.babel.js                                                 [21:38:32] Starting 'default'...                                                                                        [21:38:32] Starting 'images'...                                                                                         [21:38:32] Starting 'styles'...                                                                                         [21:38:32] Starting 'scripts'...                                                                                        [21:38:32] Starting 'store'...                                                                                          [21:38:32] Starting 'png'...                                                                                            [21:38:32] Starting 'jpg'...                                                                                            [21:38:32] Starting 'svg'...                                                                                            [21:38:32] Starting 'gif'...                                                                                            [21:38:35] gulp-imagemin: Minified 1 image (saved 1.11 kB - 0.5%)                                                       [21:38:37] Finished 'gif' after 4.82 s                                                                                  [21:38:39] Finished 'store' after 7.2 s                                                                                 [21:38:42] Finished 'styles' after 9.82 s                                                                               [21:38:47] gulp-imagemin: Minified 3 images (saved 34.6 kB - 2.5%)                                                      [21:38:47] Finished 'jpg' after 15 s                                                                                    (node:17760) UnhandledPromiseRejectionWarning: Error in parsing SVG: Non-whitespace before first tag.                   Line: 0                                                                                                                 Column: 1                                                                                                               Char: i                                                                                                                 (node:17760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)                                                                                                                (node:17760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.    
```

**Comment by lewisgoddard** [comment]
Have you made sure to `git pull` and `npm install` again? This is interestings because `npm run build` works fine on master [right now](https://travis-ci.com/elementary/website/jobs/246425524#L677).

**Comment by Erbenos** [comment]
That's interesting indeed. Yes I created new fork and cloned that one, so I am pretty sure I have latest version as of right now.

**Comment by Erbenos** [comment]
What is your Node.js version? Maybe I am getting some npm package with different version.

**Comment by Erbenos** [comment]
Hmm, I see that Travis job is running with Node 12.12.0 will try that.

**Comment by Erbenos** [comment]
I updated both Node.js and npm, and tried again, on both Windows and Ubuntu. Ubuntu works fine (just like in Travis) but Windows has some sort of pathing issue. See [powershell output](https://i.imgur.com/tciBqTl.png). Will investigate.

**Comment by Erbenos** [comment]
@lewisgoddard Seems like a multifaceted problem.

1) 'svg' task here: https://github.com/elementary/website/blob/7cf2d971060270eef506a1c892ce8f5658410253/gulpfile.babel.js#L100
fails on several whitelisted '_images/icons/<rest of path>' icons - all of the faulty ones are symlinks so it makes sense that it fails on windows, they are:
- '_images/icons/apps/symbolic/web-browser-symbolic.svg'
- '_images/icons/apps/32/accessories-camera.svg'
- '_images/icons/apps/48/ubiquity.svg'
- '_images/icons/apps/64/accessories-camera.svg'
- '_images/icons/apps/64/web-browser.svg'
- '_images/icons/devices/symbolic/computer-symbolic.svg'

To fix that I suppose it would be needed for them to actually have right contents.

2) 'scripts' tasks fails with some pathing error, wouldn't be suprised if it were something similar as above

Can we reopen the issue or is this a wontfix considering the problem only appears on Windows? Worst case scenario just add to readme "If on Linux, use WSL" - I have not tryed that yet though.

**Comment by btkostner** [comment]
We don't support building on systems other than Linux because there are a lot of inconsistencies with PHP and Node JS, especially with paths. We will accept PRs to make things work better on windows as long as it isn't _too_ extreme.

**Comment by Erbenos** [comment]
Thank you for info.

Seems I will go the WSL / Ubuntu host OS way then. Is it OK if I make PR adding above comment to CONTRIBUTING.md ?
